channels:
  - jmcmurray
  - powerai
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.6
  - os
  - pip:
      - tf2rl==0.1.12
      - tensorflow-cpu==2.2.0
      - gym
      - numpy
      - jupyter
      - pandas
      - pickle5
      - cloudpickle==1.3.0
      - matplotlib
      - argparse
      - pylint

