name: adlr_gpu
channels:
  - jmcmurray
  - powerai
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.7
  - cloudpickle=1.2.2
  - gym=0.15.3
  - importlib_resources=1.5.0
  - jupyter=1.0.0
  - numpy=1.18.1
  - pandas=1.0.3
  - pickle5=0.0.9
  - pip=20.0.2
  - pylint=2.5.2
  - tensorflow-gpu=2.1.0
  - pip:
    - matplotlib==3.2.1
    - tf2rl==0.1.12
    - argparse==1.4.0

